version: "3"
services:
  api-gateway:
    image: theuggla/api-gateway:test
    ports:
      - "80:4000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - isolation-network
  user:
    image: theuggla/user-service:test
    labels:
        api_route: '/user-service'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      SERVICE_NAME: "user-service"
    networks:
      - isolation-network
  notification:
    image: theuggla/notification-service:test
    labels:
        api_route: '/notification-service'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      SERVICE_NAME: "notification-service"
    networks:
      - isolation-network
  github:
    image: theuggla/github-service:test
    labels:
        api_route: '/github-service'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      SERVICE_NAME: "github-service"
    networks:
      - isolation-network
networks:
  isolation-network:
    driver: overlay
